name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Baut den Default-Target aus deinem Makefile (bei dir: userland/hello)
      - name: Build
        run: make

      # Optional: einmal kurz testen, ob das Binary auch läuft
      - name: Run userland/test
        run: make run TARGET=userland/test